import os
from dotenv import load_dotenv

load_dotenv()
AWS_BUCKET = os.getenv("S3_BUCKET_NAME")
AWS_REGION = os.getenv("AWS_REGION")
AWS_ACCESS_KEY = os.getenv("AWS_ACCESS_KEY")
AWS_SECRET_KEY = os.getenv("AWS_SECRET_KEY")

# SQS Queues
BOOK_PROCESSING_QUEUE_URL = os.getenv("BOOK_PROCESSING_QUEUE_URL")
NORMALIZED_BOOK_QUEUE_URL = os.getenv("NORMALIZED_BOOK_QUEUE_URL")

# DynamoDB
DDB_SUMMARIES_TABLE = os.getenv("DDB_SUMMARY_TABLE")
DDB_CHARACTERS_TABLE = os.getenv("DDB_CHARACTER_TABLE")

# Signed URL
SIGNED_URL_TTL_SEC = int(os.getenv("SIGNED_URL_TTL_SEC"))
