version = 0.1
[default.deploy.parameters]
stack_name = "read-recall-cf"
resolve_s3 = true
s3_prefix = "read-recall-cf"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "OutputBucketNameParameter=\"normalized-book-bucket\""
image_repositories = []
